from Queves import Queue
queue = Queue(2)
print(queue)
queue.enqueue(4)
print(queue)
queue.enqueue(7)
print(queue)
queue.enqueue(12)
print(queue)
queue.enqueue(41)
print(queue)
queue.dequeue()
print(queue)
queue.dequeue()
print(queue)
queue.dequeue()
print(queue)
queue.dequeue()
print(queue)